apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec: 
      containers:
      - name: grafana
        image: grafana/grafana 
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "secret"
        ports:
        - containerPort: 3000
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 60
          timeoutSeconds: 3
        volumeMounts:
        - name: grafana
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana
        flexVolume:
          driver: rexray/flexrex
          fsType: xfs
          options:
            volumeID: grafana
            service: scaleio
            forceAttach: "true"
            forceAttachDelay: "20"
